name: Social
version: ${project.version}
api-version: 1.13
main: me.prism3.socialbukkit.Main
authors: [ Prism3 ]
description: Social media corners for your server.
website: prism3.me
commands:
    Social:
        description: "Open social media Menu."
permissions:
    social.use:
        description: Open the Social Media Menu.
        default: true
    social.reload:
        description: Reload the Plugin.
        default: op