# /////////////////////////////////////////////////////////////
# /                                                           /
# /                      Social Plugin                        /
# /                                                           /
# /                    [ Proxy Version ]                      /
# /                                                           /
# /////////////////////////////////////////////////////////////
#
# Thank you for using Social Plugin! If you are experiencing any issues
# or have any suggestions / features you want to be implemented into the plugin
# feel free to join the support Discord Server!
#
# Spigot: Prism3
# Discord: Prism3#9371 | ID: 403667971089760257
# Discord Server: https://discord.gg/MfR5mcpVfX


# Social
Links:
  Website:
    Link: "&f&lWebsite.com"
  Youtube:
    Link: "&c&lYoutube.com"
  Facebook:
    Link: "&b&lFacebook.com"
  Twitch:
    Link: "&5&lTwitch.com"
  Discord:
    Link: "&9&lDiscord.gg"
  Instagram:
    Link: "&d&lInstagram.com"
  Store:
    Link: "&6&lStore.com"


Messages:
  Prefix: "&9&lSocial &8&l|"
  No-Permission: "&cYou do not have permission to use this command!"
  Invalid-Syntax: "&cInvalid Syntax."
  Reload: "&a&lSocial has been reloaded!"
