# /////////////////////////////////////////////////////////////
# /                                                           /
# /                      Social Plugin                        /
# /                                                           /
# /                   [ Velocity Version ]                    /
# /                                                           /
# /////////////////////////////////////////////////////////////
#
# Thank you for using Social Plugin! If you are experiencing any issues
# or have any suggestions / features you want to be implemented into the plugin
# feel free to join the support Discord Server!
#
# Spigot: Prism3
# Discord: Prism3#9371 | ID: 403667971089760257
# Discord Server: https://discord.gg/MfR5mcpVfX


# Social
Links:
  Website:
    Link: "Website.com"
    Color: "#FFFFFF"
  Youtube:
    Link: "Youtube.com"
    Color: "#FF0000"
  Facebook:
    Link: "Facebook.com"
    Color: "#0000FF"
  Twitch:
    Link: "Twitch.com"
    Color: "#800080"
  Discord:
    Link: "Discord.gg"
    Color: "#000080"
  Instagram:
    Link: "Instagram.com"
    Color: "#FFC0CB"
  Store:
    Link: "Store.com"
    Color: "#FFD700"


# Plugin Messages
Messages:
  Prefix: "Social | "
  No-Permission: "You do not have permission to use this command!"
  Invalid-Syntax: "Invalid Syntax."
  Reload: "been reloaded!"

Colors:
  Prefix: "#ADD8E6"
  No-Permission: "#FF0000"
  Invalid-Syntax: "#FF0000"
  Reload: "#90EE90"
